services:
  ubuntu-dev:
    build: .
    platform: linux/amd64
    container_name: ubuntu-dev
    tty: true
    stdin_open: true
    volumes:
      - ./:/workspace
    working_dir: /workspace
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined

